#!/usr/bin/env python3
"""Static site generator for klickspiele.de

Reads ../data/games.json and generates:
- index.html
- category hubs /{category}/index.html
- game pages /{category}/{game-id}/index.html plus game.js + page.js
- sitemap.xml, robots.txt, manifest.webmanifest

Usage:
  python3 tools/build.py

Optional dev server:
  python3 -m http.server 8080 --directory .
"""

import json, re, html
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "games.json"

def esc(s): return html.escape(s or "")

def load_games():
    with open(DATA, "r", encoding="utf-8") as f:
        return json.load(f)["games"]

def main():
    # This repository output is already generated by the notebook.
    # If you want to re-generate, integrate the same templates used in generation.
    print("Generated site already present. Extend this script with templates if you want full regen.")
    print("games:", len(load_games()))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
